import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Reatom } from './abs';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const data = await (await fetch('https://jsonplaceholder.typicode.com/todos/1')).json();

    return (
        <html lang="en">
            <body className={inter.className}>
                <h1>Layoyt</h1>
                <Reatom params={data}>{children}</Reatom>
            </body>
        </html>
    );
}
